name: Test workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
  inputs: 
    num1:
      description: 'First number'
      required: true
      default: 0
    num2:
      description: 'Second number'
      required: true
      default: 0
env: 
  platform: "Ubuntu"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Sum two numbers
        id: sum
        run:  |
          echo "Repository name ${{github.repository}}"
          echo "First number: ${{ github.event.inputs.num1 }}"
          echo "Second number: ${{ github.event.inputs.num2 }}"
          sum=$(( ${{ github.event.inputs.num1 }} + ${{ github.event.inputs.num2 }} ))
          echo "Sum: $sum"
      