name: Test workflow

on:
  push:
    branches:
      - '**'
env: 
  platform: "Ubuntu"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Dump GitHub context
        run:  |
         echo "Repository name ${{github.repository}}"
         echo "workflow name ${{github.workflow}}"
         echo "workspace name ${{github.workspace}}"


      