name: Test workflow

on:
  push:
    branches:
      - '**'
env: 
  platform: "Ubuntu"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Hello $name, this workflow is running on $platform , ${{ vars.TestVariable }}"
        env: 
          name: "Vinit"